### ISSUE TITLE
Automatically detect WLAN device name on newer devices

### ISSUE THREAD

**Issue by peteroid** [mvdan/libaccesspoint#11]
When I tested with this nice library on the LG phone, all the things work like a charm. If I switch to Samsung S7, the `getClients` function seems broken. I tried to dig into the code. It seems that the `devicename` for the AP on S7 is `swlan0`. But the `devicename` was fallback to `wlan0` because it is Marshmallow.

Can we specify the `devicename` explicitly instead?

**Comment by mvdan** [comment]
See the discussion in #12.

In particular, this is about a way to detect the wireless device name on newer devices. Our existing method using MAC address matching doesn't work on 6.0 and later since MAC addresses are hidden on those versions of Android.

If a new method works on older versions of Android too, perhaps the MAC method could be replaced entirely.

**Comment by mvdan** [comment]
There seems to be no interest in this, so I'm closing the issue for now. I don't personally know of a good method to make this automatic.
